# Generated by Django 3.1.3 on 2020-12-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coutry', models.CharField(max_length=100)),
                ('trophies', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the position of player (e.g. Central Midfielder, Centarl Defender etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField(help_text='Enter description of the player', max_length=1000)),
                ('age', models.CharField(help_text='13 Character <a href="enter age of the player</a>', max_length=13, verbose_name='Age')),
                ('current_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.club')),
                ('position', models.ManyToManyField(help_text='Select a position of player', to='catalog.Position')),
            ],
        ),
    ]
