# Generated by Django 3.1.3 on 2020-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_player_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.TextField(help_text='Enter description of the player', max_length=1000, null=True),
        ),
    ]
