# Generated by Django 3.1.3 on 2020-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201213_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
