# Generated by Django 3.1.3 on 2020-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201213_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='title',
            new_name='Full_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
