# Generated by Django 3.1.3 on 2020-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201213_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='information',
            field=models.TextField(help_text='Enter description of the player', max_length=100),
        ),
    ]
